### ISSUE TITLE
Requesting to add tags

### ISSUE THREAD

**Issue by vinay-keshava** [maraisr/meros#17]
Requesting to add tags to your repository .

- Debian Packaging (Javascript team)

**Comment by maraisr** [comment]
sounds good. I'll get this sorted 🤝

**Comment by vinay-keshava** [comment]
Thank you

**Comment by maraisr** [comment]
Hi there @vinay-keshava  I have added git tags to all the v1+ commits, stuff prior/beta has not been tagged.

From here on out I will tag all releases as well as create GitHub releases for those.

Cheers,

**Comment by vinay-keshava** [comment]
Thank you @maraisr for the faster response
Cheers!
