### ISSUE TITLE
Boundary parser

### ISSUE THREAD

**Issue by artola** [maraisr/meros#18]
### Describe the bug

This `Content-Type: multipart/mixed;boundary="-";charset=utf-8` leads to the following wrong boundary `---;charset=utf-8`.

The shape is `"Content-Type"  ":" type "/" subtype  *(";" parameter)` from [RFC 1521 page 69](https://www.ietf.org/rfc/rfc1521.txt).

The code involved is related to the calculation of the boundary:

https://github.com/maraisr/meros/blob/183f788f170e2cac4c6cde621701428983ecb294/src/browser.ts#L105

It could be fixed looking ahead for the `;` and removing anything after:

```javascript
ctype.substring(idx_boundary + 9).replace(/;.*/g, '').trim().replace(/['"]/g, '')
```

Please let me know if you handle the fix or if I should PR this little change.

**Note**: `meros` is used in our client `Banana Cake Pop`. @maraisr Thanks for your support to the OSS.

### To reproduce

`Content-Type: multipart/mixed;boundary="-";charset=utf-8` incorrectly leads to a boundary `---;charset=utf-8`

### Expected behavior

`Content-Type: multipart/mixed;boundary="-";charset=utf-8` must lead to a boundary `---`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/maraisr/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/maraisr/.github/blob/main/CONTRIBUTING.md).
- [X] Is there already an issue for this?

**Comment by maraisr** [comment]
Hi @artola thanks for this 🙏🏻  I have pushed a patch that should have that resolved that issue, thanks for letting me know. I also added a test for that case, let me know what you think. v1.2.1 should be the goer.

**Comment by artola** [comment]
> Hi @artola thanks for this 🙏🏻 I have pushed a patch that should have that resolved that issue, thanks for letting me know. I also added a test for that case, let me know what you think. v1.2.1 should be the goer.

@maraisr Thanks. Your fix LGTM.

**Comment by artola** [comment]
@maraisr  The fix is OK and  the token must not include `;` as you mention above and stated in the spec page 32-33.
Same interpretation made yesterday with @rstaib.
