### ISSUE TITLE
How to properly mock responses for testing?

### ISSUE THREAD

**Issue by Dzieni** [maraisr/meros#19]
It's more of a question or a documentation suggestion than a solid issue, hopefully that's OK for you.

I'm writing a Node.js application in which I'd like to process multipart response using `meros`. I'm using [WHATWG `fetch` provided with Node](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch), so I'm interested in `meros/browser`.

To ensure I'm processing the data correctly I'd like to make a test suite in which I'll provide some responses and check if I'm happy with the final result.

The problem is I don't know how to properly create `Response` objects for such a test suite. I've tried running the basic example from your repo and using the response body in `new Response` constructor. The solution seems to be working correctly for methods like `res.text()`. The problem is that in that case the async generator returned by `meros` does not yield anything.

Here is the snippet: https://stackblitz.com/edit/vitejs-vite-9mzij1?file=main.js. It runs in the browser to ensure that my problems are not caused by using browser library in Node.js.

Could you please provide some hint? Thanks in advance :)

**Comment by maraisr** [comment]
Hi there, 

Apologies for the late reply! The line ending is by spec a `CRLF` _aka_ `\r\n` (**C**arriage **R**eturn **L**ine **F**eed) not just a `\n`.

In javascript if you press enter that is simply adding a `\n` (see more https://stackoverflow.com/a/3451192). But we still need that CR moment:

If you simply put a `\r` at the end of every line in your stackblitz, works as expected for me:

```
---\r
content-type: application/json;charset=utf-8\r
\r
{"letter":"A"}\r
\r
---\r
content-type: application/json;charset=utf-8\r
\r
{"letter":"B"}\r
\r
---\r
...
```

the significance of the CR im uncertain about — but servers return this char, so if i was to make this relaxed, it will be unclear if the CR is part of the message or part of the delimiter.

So for now, the parts will look a little ugly — sorry!
